### ISSUE TITLE
FFI::NotFoundError: Function 'zlistx_head' not found on Mac

### ISSUE THREAD

**Issue by kozo2** [paddor/cztop#9]
## The error log

```
irb(main):002:0> require 'cztop'
LoadError: no library specified
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb:162:in `ffi_libraries'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb:240:in `attach_function'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen/signals.rb:4:in `<module:FFI>'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen/signals.rb:2:in `<module:CZMQ>'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen/signals.rb:1:in `<top (required)>'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen.rb:4:in `require_relative'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen.rb:4:in `<top (required)>'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cztop-0.5.0/lib/cztop.rb:1:in `<top (required)>'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from (irb):2
    from /Users/knishida/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
irb(main):003:0> 
```
## How to reproduce the error

```
brew install rbenv zeromq czmq
rbenv install 2.3.1
rbenv global 2.3.1
gem install cztop
irb
```
## Versions
- OSX 10.11.6
- rbenv 1.0.0
- zeromq 4.1.5
- czmq 3.0.2

**Comment by paddor** [comment]
I'm not sure about this error, but it's likely that the reason is that you didn't install master versions of zmq and czmq. Run "brew install --HEAD zeromq czmq". Also, you might wanna install libsodium as well.

**Comment by kozo2** [comment]
@paddor I'm sorry the log changed after I restarted the `irb` session (I didn't restart the session after installing zeromq and czmq).
Now the log says `Function 'zlistx_head' not found`

```
~/ > irb 
irb(main):001:0> require 'cztop'
FFI::NotFoundError: Function 'zlistx_head' not found in [/usr/local/lib/libczmq.dylib]
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb:261:in `attach_function'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen/czmq/ffi.rb:410:in `<module:FFI>'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen/czmq/ffi.rb:10:in `<module:CZMQ>'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen/czmq/ffi.rb:9:in `<top (required)>'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen.rb:1:in `require_relative'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen.rb:1:in `<top (required)>'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cztop-0.5.0/lib/cztop.rb:1:in `<top (required)>'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
    from /Users/knishida/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from (irb):1
    from /Users/knishida/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
irb(main):002:0> 
```

**Comment by paddor** [comment]
I still think you are using the stable versions, unless they actually removed zlistx_head from CZMQ. Sorry, i'm not up-to-date. I could check in a few days, as that's when I'll be using this library during my bachelor thesis. :)

**Comment by paddor** [comment]
This is the problem:

> zeromq 4.1.5
> czmq 3.0.2

You have to use master versions for now, until ZMQ 4.2 and CZMQ >3.0.2 are released.

**Comment by paddor** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;6GRhCqYn&#x2F;1-test"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> test</a>

**Comment by kozo2** [comment]
@paddor I moved from OSX 10.11 to 10.12.
Now I can not reproduce this error, however on 10.12 cztop worked.
I wanted to inform you that `require "cztop"` worked on 10.12 + homebrew 1.0.0

https://github.com/zeromq/libzmq/issues/2119#issuecomment-248552107

**Comment by paddor** [comment]
Thanks for the info!
